Use flywheel-io/healthcare-api client
flywheel-apps/ghc-import pull request #1
Opened 2019-06-05 15:37 UTC by davidfarkas

2019-07-10 13:28 UTC, davidfarkas reviewed
Some minor comments, otherwise LGTM. (tried to only check @denesd's changes )

2019-07-10 13:28 UTC, davidfarkas commented on .coverage
> +!coverage.py: This is a private format, don't read it directly!{"lines":{"/src/run.py":[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,31,32,33,34,38,39,40,44,92,136,187,242,251,264
please "git"ignore `.coverage` file

2019-07-10 13:28 UTC, davidfarkas commented on Dockerfile
> +RUN pip install -r tests/requirements.txt
missing new line at the end of file

2019-07-10 13:28 UTC, davidfarkas commented on tests/bin/docker-test.sh
> +    -B, --no-build      Skip building reaper image
change `reaper`

2019-07-10 13:28 UTC, davidfarkas commented on tests/bin/tests.sh
> +Assumes running in test container or that flywheel_migration and all of its
flywheel_migration?

2019-07-10 13:28 UTC, davidfarkas commented on manifest.json
> +	"description": "Import dicoms from Google Healthcare API",
Use uppercase `DICOM`'s here too as you did elsewhere

2019-07-11 08:33 UTC, ambrussimon requested changes

2019-07-11 08:33 UTC, ambrussimon commented on Dockerfile
> +    && rm -rf /var/cache/apk/*
Doesn't `--no-cache` already take care of this?

2019-07-11 08:33 UTC, ambrussimon commented on .dockerignore
> +!script.py
This seems outdated.

2019-07-11 08:33 UTC, ambrussimon commented on Dockerfile
> +RUN pip3 install -r requirements.txt \
I would suggest keeping the copying of reqs and their installation close together (ie. no empty line).

2019-07-11 08:33 UTC, ambrussimon commented on manifest.json
> +			"description": "JSON file with DICOM Series Instance or Study Instance UIDs, HL7 Message IDs , FHIR Resource References. Schema: {'dicoms': ['1.2.840.113619.2.243.4231785106118302.10626.7104.13962
Study/SeriesInstanceUIDs. Could you check on other gears, maybe there's an already established (nicer) way of handling longer descriptions. Also, `import_ids` is not very descriptive as it is (not that I have an alternative...)

2019-07-11 08:33 UTC, ambrussimon commented on run.py
> +import re
Imports are not in order.

2019-07-11 08:33 UTC, ambrussimon commented on run.py
> +log = logging.getLogger('ghc_import')
Gear contexts have helpers for setting up logging, too.

2019-07-11 08:33 UTC, ambrussimon commented on run.py
> +class FwApi(requests.Session):
You may as well pass the key and adjust the headers in the constructor IMO.

2019-07-11 08:33 UTC, ambrussimon commented on tests/requirements.txt
> +pytest
Requirements are not in order.

2019-07-11 08:33 UTC, ambrussimon commented on tests/bin/docker-test.sh
> +#!/usr/bin/env sh
The `docker-tests` and `tests.sh` pattern was ported rather hastily and lazily.
There's a bunch of lines that were just copied without any thought to it (`see tests.sh` L# 28-34).
Test requirements aren't heavy at all - I recommend just
- removing these wrappers
- requiring users to install the requirements and run pytest locally
- automating the same for CI

2019-07-17 11:30 UTC, ambrussimon approved these changes
Well done, this looks good to me!

2019-07-17 11:30 UTC, ambrussimon commented on run.py
> +    log.debug('config.json\n%s', pprint.pformat(config))
Is this logging more than what's available via `context.log_config()`?

2019-07-17 11:30 UTC, ambrussimon commented on run.py
> +from urllib.parse import urljoin
Minor complaint here: `urllib` is in core, `pytz` and `requests` isn't, and there's no empty line dividing core/3rd-party imports.

2019-07-18 11:41 UTC, davidfarkas commented on run.py
> +    resp = fw_api.get('projects/' + config['project_id'])
I think we should minimize the usage of custom api clients. I suppose that we can use the SDK to validate that the project exists or not.
@ambrussimon any thoughts?

2019-07-24 09:02 UTC, davidfarkas commented on run.py
> +    resp = fw_api.get('projects/' + config['project_id'])
Never mind, I will open a PR soon which includes this change.

2019-07-24 09:02 UTC, merged